
OPENAI_API_KEY = "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"
GROQ_API_KEY = "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"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_TRACING_V2 = "true"